### ISSUE TITLE
파이썬에서 UTF-8을 못 읽은 문제

### ISSUE THREAD

**Issue by Jin02** [Jin02/SOCEngine#83]
1>Traceback (most recent call last):
1>  File "E:\Projects\GitHub\SOCEngine\SOCEngine\SOCEngine\..\..\Script\HLSLMetaDataGenerator.py", line 550, in <module>
1>    result = Work(shaderFilePath, path+'\\', metaDataFilePath, useEasyView)
1>  File "E:\Projects\GitHub\SOCEngine\SOCEngine\SOCEngine\..\..\Script\HLSLMetaDataGenerator.py", line 312, in Work
1>    firstLine 	= shaderFile.readline()
1>UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 2365: illegal multibyte sequence

**Comment by Jin02** [comment]
This issue was moved to TeamSOC/SOCEngine#83
